services:
  backend:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - wiremock
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      EXTERNAL_SERVICE_URL: http://wiremock:8080/api/v1/porcentaje
      LOGGING_FILE_PATH: //backend/Logs
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  wiremock:
    image: rodolpheche/wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./mocks:/home/wiremock
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
